apiVersion: apps/v1
kind: Deployment
metadata:
  name: assignment3-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: assignment3-backend
  template:
    metadata:
      labels:
        app: assignment3-backend
    spec:
      containers:
      - name: backend
        image: aahanjain1411/assignment3-backend:v1
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  type: NodePort
  selector:
    app: assignment3-backend
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30080   # Accessible via http://localhost:30080
