apiVersion: apps/v1
kind: Deployment
metadata:
  name: assignment3-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: assignment3-frontend
  template:
    metadata:
      labels:
        app: assignment3-frontend
    spec:
      containers:
      - name: frontend
        image: aahanjain1411/assignment3-frontend:v1

        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: NodePort
  selector:
    app: assignment3-frontend
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30000   # Accessible via http://localhost:30000
